In [6]:
int(False)

0

In [20]:
import numpy as np

prediction = np.array([True,False,False,False,True,False])
true_class = [1,0,1,1,1,0]
'''
for i in range(len(prediction)):
    if prediction[i] == true_class[i]:
        correct_prediction.append(prediction[i])
accuracy = len(correct_prediction)/len(prediction)
print("Correct Prediction: {}"
      "\nAccuracy: {}".format(correct_prediction, accuracy))
'''
correct_prediction = prediction == true_class
accuracy = correct_prediction.mean()
print("Correct Prediction: {}"
      "\nAccuracy: {}".format(correct_prediction, accuracy))


Correct Prediction: [ True  True False False  True  True]
Accuracy: 0.6666666666666666


In [18]:
correct_prediction = prediction == true_class
print(correct_prediction)

False


In [23]:
rand = np.random.uniform(-1, 1, (4,))
print(rand)

[ 0.19207062  0.67880475 -0.74861576 -0.32581256]


In [25]:
import spacy
from spacy.symbols import ORTH

In [35]:
nlp = spacy.load("en_core_web_sm")
doc = nlp("gimme that")
print([w.text for w in doc])

['gimme', 'that']


In [27]:
#define a special case
special_case = [{ORTH: "gim"}, {ORTH: "me"}]
nlp.tokenizer.add_special_case("gimme", special_case)
print([w.text for w in nlp("gimme that")])

['gim', 'me', 'that']


In [32]:
doc = nlp("I live in NewYorkCity")
with doc.retokenize() as retokenizer:
    heads = [(doc[3], 0),(doc[3], 1),(doc[3], 2)]
    retokenizer.split(doc[3], ['New', 'York', 'City'], heads=heads)
print([token.text for token in doc])

['I', 'live', 'in', 'New', 'York', 'City']


In [36]:
from spacy.language import Language

text = "this is a sentence...hello...and another sentence."
doc = nlp(text)
print("Before: ", [sent.text for sent in doc.sents])

@Language.component("set_custom_boundaries")
def set_custom_boundaries(doc):
    for token in doc:
        if token.text == "...":
            doc[token.i+1].is_sent_start = True
    return doc

nlp.add_pipe("set_custom_boundaries", before="parser")
doc = nlp(text)
print("After: ", [sent.text for sent in doc.sents])

Before:  ['this is a sentence...', 'hello...and another sentence.']
After:  ['this is a sentence...', 'hello...', 'and another sentence.']


In [39]:
nlp = spacy.load("en_core_web_md")
tokens = nlp("abcdefg afskfsd")

for token in tokens:
    print(token.text, token.has_vector, token.vector_norm, token.is_oov)

abcdefg True 7.4450955 False
afskfsd False 0.0 True


In [43]:
nlp = spacy.load("en_core_web_md")
doc1 = nlp("Hardware issue on my laptop")
doc2 = nlp("I have an issue on my laptop, i think it is about the hardware side")

print(f"{doc1.text} <-> {doc2.text} Similarity: {doc1.similarity(doc2):.3f}")

Hardware issue on my laptop <-> I have an issue on my laptop, i think it is about the hardware side Similarity: 0.846


In [47]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [53]:
# define the documents
corpus = ["i cant wait to get out of lockdown", "the uk is soon going to be free soon", "linkedin is social media"]

#converting text to integer
token_docs = [doc.split() for doc in corpus]
all_tokens = set([word for sentence in token_docs for word in sentence])
print("token_docs: ",token_docs)
print("all_tokens: ",all_tokens)
word_to_idx = {token:idx+1 for idx, token in enumerate(all_tokens)}
print("word_to_idx", word_to_idx)

#converting the doc to their id
token_idx = np.array([[word_to_idx[token] for token in token_doc] for token_doc in token_docs], dtype=object)
print("\ntoken_idx: ", token_idx)

token_docs:  [['i', 'cant', 'wait', 'to', 'get', 'out', 'of', 'lockdown'], ['the', 'uk', 'is', 'soon', 'going', 'to', 'be', 'free', 'soon'], ['linkedin', 'is', 'social', 'media']]
all_tokens:  {'soon', 'linkedin', 'is', 'to', 'cant', 'out', 'of', 'uk', 'be', 'i', 'media', 'going', 'social', 'get', 'free', 'the', 'lockdown', 'wait'}
word_to_idx {'soon': 1, 'linkedin': 2, 'is': 3, 'to': 4, 'cant': 5, 'out': 6, 'of': 7, 'uk': 8, 'be': 9, 'i': 10, 'media': 11, 'going': 12, 'social': 13, 'get': 14, 'free': 15, 'the': 16, 'lockdown': 17, 'wait': 18}

token_idx:  [list([10, 5, 18, 4, 14, 6, 7, 17]) list([16, 8, 3, 1, 12, 4, 9, 15, 1])
 list([2, 3, 13, 11])]


#### Bag of Word (BoW)

In [70]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# define the documents
corpus = ["I cant wait to get out of lockdown", "the uk is soon going to be free soon", "linkedin is social media"]

# implement bow
bow = CountVectorizer()
bow.fit(corpus)
X = bow.transform(corpus)

# convert X to df
print(X, X.toarray())

  (0, 1)	1
  (0, 3)	1
  (0, 7)	1
  (0, 9)	1
  (0, 10)	1
  (0, 14)	1
  (0, 16)	1
  (1, 0)	1
  (1, 2)	1
  (1, 4)	1
  (1, 5)	1
  (1, 12)	2
  (1, 13)	1
  (1, 14)	1
  (1, 15)	1
  (2, 5)	1
  (2, 6)	1
  (2, 8)	1
  (2, 11)	1 [[0 1 0 1 0 0 0 1 0 1 1 0 0 0 1 0 1]
 [1 0 1 0 1 1 0 0 0 0 0 0 2 1 1 1 0]
 [0 0 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0]]


In [71]:
X_train = bow.fit_transform(corpus)
print(X_train)

  (0, 1)	1
  (0, 16)	1
  (0, 14)	1
  (0, 3)	1
  (0, 10)	1
  (0, 9)	1
  (0, 7)	1
  (1, 14)	1
  (1, 13)	1
  (1, 15)	1
  (1, 5)	1
  (1, 12)	2
  (1, 4)	1
  (1, 0)	1
  (1, 2)	1
  (2, 5)	1
  (2, 6)	1
  (2, 11)	1
  (2, 8)	1


In [85]:
from collections import Counter
words = ['John', 'likes', 'to', 'watch', 'movies.', 'Mary', 'likes', 'movies', 'too.']
counts = Counter(words).most_common()
X = {}
for item in counts:
    for i in range(len(item)-1):
        X[item[i]] = item[i+1]
print(X)


{'likes': 2, 'John': 1, 'to': 1, 'watch': 1, 'movies.': 1, 'Mary': 1, 'movies': 1, 'too.': 1}


In [86]:
len({"John":2,"likes":3,"to":2,"watch":2,"movies":2,"Mary":1,"too":1,  "also":1,"football":1,"games":1})

10

##### BOW freecodecamp

In [34]:
import nltk
import numpy as np
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [42]:
def word_extraction(text):
    stop_words = set(stopwords.words("english"))
    word_tokens = word_tokenize(text.lower())
    filtered_word = [word for word in word_tokens if word not in stop_words]
    return filtered_word

def tokenize_all(texts):
    words = []
    for text in texts:
        words.extend(word_extraction(text))
    return sorted(list(set(words)))

def generate_bow(texts):
    vocab = tokenize_all(texts)
    bags = {}
    for index, text in enumerate(texts):
        bag = np.zeros(len(vocab))
        words = word_extraction(text)
        for w in words:
            for idx, word in enumerate(vocab):
                if word == w:
                    bag[idx] +=1
        bags[index] = bag
    return bags

In [43]:
texts = ["Joe waited for the train", "The train was late", "Mary and Samantha took the bus",
         "I looked for Mary and Samantha at the bus station",
         "Mary and Samantha arrived at the bus station early but waited until noon for the bus"]
words = generate_bow(texts)
print(words)

{0: array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1.]), 1: array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.]), 2: array([0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0.]), 3: array([0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0.]), 4: array([1., 2., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1.])}


##### N-grams

In [52]:
a = ["The","sun","rise", "east"]
temp = [a[i:] for i in range(0,3)]
temps = zip(*temp) # *list = unpack the list
print(temp)
print(list(temps))

[['The', 'sun', 'rise', 'east'], ['sun', 'rise', 'east'], ['rise', 'east']]
[('The', 'sun', 'rise'), ('sun', 'rise', 'east')]
